<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Device;
use Illuminate\Support\Facades\DB;
class DevicesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $devices = [
            [
                "id" => "49",
                "is_active" => "0",
                "signal_strength" => "80",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "2.5",
                "device_id" => "c17go7d17uj000bpr9i0",
                "name" => "02/Kjølebenk",
                "description" => "Diego Pizzacxvgffdx",
                "device_status" => "0",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2022-09-20 16:33:59",
                "updated_at" => "2022-12-02 05:05:53",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2022-11-30 14:42:49",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "2",
                "labels_json" => null,
                "not_available" => "58",
                "specification" => "dsfdsfsdvfsdsv",
            ],
            [
                "id" => "52",
                "is_active" => "0",
                "signal_strength" => "48",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "31.55",
                "device_id" => "c095l4fqbveg00fetasg",
                "name" => "",
                "description" => "Karls Fisk og Skalldyr (Manndalen)",
                "device_status" => "0",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2022-09-20 18:36:15",
                "updated_at" => "2022-12-13 16:58:36",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2022-12-13 16:10:40",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "3",
                "labels_json" => null,
                "not_available" => "2",
                "specification" => "MT_slifnewkfaøkb82e76278",
            ],
            [
                "id" => "53",
                "is_active" => "0",
                "signal_strength" => "58",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "-23.6",
                "device_id" => "c1488lt17uj000bpop20",
                "name" => "10/Freezer 3rd floor",
                "description" => "",
                "device_status" => "0",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2022-09-20 18:36:15",
                "updated_at" => "2022-12-02 05:05:53",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2022-11-30 14:38:34",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "5",
                "labels_json" => null,
                "not_available" => "60",
                "specification" => null,
            ],
            [
                "id" => "54",
                "is_active" => "1",
                "signal_strength" => "95",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "23.15",
                "device_id" => "c095u9p6895g00821p4g",
                "name" => "c095u9p6895g00821p4g",
                "description" => "",
                "device_status" => "1",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2022-09-20 18:36:15",
                "updated_at" => "2023-11-01 14:40:14",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2023-11-01 14:40:12",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "14",
                "labels_json" => null,
                "not_available" => "59",
                "specification" => " ",
            ],
            [
                "id" => "56",
                "is_active" => "0",
                "signal_strength" => "60",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "9.25",
                "device_id" => "c14u1d517uj000bpqbn0",
                "name" => "09/Wine room",
                "description" => "sdfsdfdsfsdfsdfsdfsdfsdf",
                "device_status" => "0",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2022-09-20 18:36:16",
                "updated_at" => "2022-12-02 05:05:53",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2022-11-25 11:40:14",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "6",
                "labels_json" => null,
                "not_available" => "60",
                "specification" => "sdfsfsdfdsfdsfdsfsfdsfsffsdf",
            ],
            [
                "id" => "57",
                "is_active" => "0",
                "signal_strength" => "68",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "5.4",
                "device_id" => "c148i2l17uj000bpp0eg",
                "name" => "01/Fridge",
                "description" => "",
                "device_status" => "0",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2022-09-20 18:36:17",
                "updated_at" => "2022-12-02 05:05:53",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2022-11-30 14:41:33",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "7",
                "labels_json" => null,
                "not_available" => "60",
                "specification" => null,
            ],
            [
                "id" => "132",
                "is_active" => "0",
                "signal_strength" => "90",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "-19",
                "device_id" => "bhqh01mt96bg00813nsg",
                "name" => "Kafé 09/Fryseskap liten",
                "description" => "Munch Museet",
                "device_status" => "0",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2022-10-12 09:31:33",
                "updated_at" => "2022-12-02 05:05:53",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2022-11-25 11:52:46",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "4",
                "specification" => null,
            ],
            [
                "id" => "187",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "TmJuK8ed2RjysVZK2gUe",
                "name" => "Strafelaten12",
                "description" => "Kjøpt i 2021234",
                "device_status" => "0",
                "event_type" => "equipment",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2022-12-27 11:15:05",
                "updated_at" => "2023-07-04 07:05:00",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "Dl2134512",
            ],
            [
                "id" => "188",
                "is_active" => "0",
                "signal_strength" => "15",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "29.45",
                "device_id" => "c8kaveasffvg00bpmnug",
                "name" => "Just a name, and edit.",
                "description" => "soemthing",
                "device_status" => "1",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "HIGH_POWER_BOOST_MODE",
                "coming_from_id" => "0",
                "created_at" => "2022-12-29 15:20:43",
                "updated_at" => "2023-07-12 11:54:59",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2023-03-02 14:28:57",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "2",
                "labels_json" => null,
                "not_available" => "0",
                "specification" => null,
            ],
            [
                "id" => "190",
                "is_active" => "0",
                "signal_strength" => "5",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "22.75",
                "device_id" => "c8kaveasffvg00bpmo3g",
                "name" => "",
                "description" => "",
                "device_status" => "1",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "HIGH_POWER_BOOST_MODE",
                "coming_from_id" => "0",
                "created_at" => "2023-01-05 21:59:37",
                "updated_at" => "2023-02-21 13:20:01",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2023-02-10 13:30:10",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "12",
                "labels_json" => null,
                "not_available" => "0",
                "specification" => null,
            ],
            [
                "id" => "213",
                "is_active" => "1",
                "signal_strength" => "100",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "25.5",
                "device_id" => "c3mjf7310j50008unq30",
                "name" => "Test sensorr",
                "description" => "",
                "device_status" => "1",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2023-02-28 15:48:04",
                "updated_at" => "2023-11-01 14:27:37",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2023-11-01 14:27:36",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "4",
                "labels_json" => null,
                "not_available" => "0",
                "specification" => " ",
            ],
            [
                "id" => "215",
                "is_active" => "0",
                "signal_strength" => "66",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "22.7",
                "device_id" => "c3im6cr10j50008umm2g",
                "name" => "Test2",
                "description" => "",
                "device_status" => "0",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2023-03-04 11:13:35",
                "updated_at" => "2023-06-30 12:14:17",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2023-06-30 12:14:16",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "10",
                "labels_json" => null,
                "not_available" => "2",
                "specification" => null,
            ],
            [
                "id" => "216",
                "is_active" => "0",
                "signal_strength" => "100",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "28.25",
                "device_id" => "c3im6638crq000983fd0",
                "name" => "",
                "description" => "",
                "device_status" => "0",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2023-03-06 09:22:28",
                "updated_at" => "2023-04-11 10:53:20",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2023-04-11 10:53:18",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "3",
                "labels_json" => null,
                "not_available" => "2",
                "specification" => null,
            ],
            [
                "id" => "223",
                "is_active" => "0",
                "signal_strength" => "70",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "cf7c2q2o0001ml62p930",
                "name" => "",
                "description" => "",
                "device_status" => "0",
                "event_type" => "ccon",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "1",
                "created_at" => "2023-03-30 04:51:38",
                "updated_at" => "2023-04-03 12:30:16",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2023-04-03 12:30:15",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "2",
                "specification" => null,
            ],
            [
                "id" => "249",
                "is_active" => "1",
                "signal_strength" => "75",
                "battery_level" => "100",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "28.05",
                "device_id" => "c8kaveasffvg00bpmnv0",
                "name" => "Mashkraft sensor 2",
                "description" => "",
                "device_status" => "1",
                "event_type" => "temperature",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => "LOW_POWER_STANDARD_MODE",
                "coming_from_id" => "0",
                "created_at" => "2023-05-30 09:41:17",
                "updated_at" => "2023-11-01 14:32:20",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => "2023-11-01 14:32:19",
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => "8",
                "labels_json" => null,
                "not_available" => "0",
                "specification" => null,
            ],
            [
                "id" => "275",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "bUhkT19oEdS5Tukpao5T",
                "name" => "Dell Laptop",
                "description" => "",
                "device_status" => "0",
                "event_type" => "equipment",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-06-21 06:11:43",
                "updated_at" => "2023-07-04 07:25:44",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "",
            ],
            [
                "id" => "276",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "9yfoO67O5gNsupEG8DlI",
                "name" => "Hp laptop",
                "description" => "",
                "device_status" => "0",
                "event_type" => "equipment",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-06-21 07:07:35",
                "updated_at" => "2023-07-04 07:25:04",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "",
            ],
            [
                "id" => "278",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "NiSzxda14eVC9455cy5H",
                "name" => "Apple",
                "description" => "",
                "device_status" => "0",
                "event_type" => "equipment",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-06-23 04:31:19",
                "updated_at" => "2023-07-04 07:31:18",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "",
            ],
            [
                "id" => "279",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "DPaM6tq0uhlp0NheUAl6",
                "name" => "inventory test",
                "description" => "gfvhvvhjg",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "0",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-07-05 09:02:20",
                "updated_at" => "2023-07-05 09:02:20",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "hkfvhkgfki",
            ],
            [
                "id" => "280",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "UQDg2gspzlaMPexQqHfd",
                "name" => "New inven",
                "description" => "fhxd",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "1",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-07-05 09:27:39",
                "updated_at" => "2023-07-05 09:27:39",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "gfyuc",
            ],
            [
                "id" => "288",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "O6wi4aqdM1GGxe2QGks2",
                "name" => "Second inventory",
                "description" => "qwert",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "55",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-07-06 12:09:43",
                "updated_at" => "2023-07-06 12:09:43",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "",
            ],
            [
                "id" => "322",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "Aj0BLDz5eSMgVE0ViIUe",
                "name" => "Oppvaskmaskin 1",
                "description" => "Beskrivelse",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "44",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-07-16 22:13:26",
                "updated_at" => "2023-07-16 22:13:26",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "Spesifikasjoner",
            ],
            [
                "id" => "338",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "KGB35P2KDvIwd7VT3euL",
                "name" => "Test",
                "description" => "qwerty",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "55",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-10-03 07:37:33",
                "updated_at" => "2023-10-03 07:37:33",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "8 gb ram",
            ],
            [
                "id" => "339",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "6XaTbWRQsznwJu0DmjJd",
                "name" => "offline device",
                "description" => "recasoft-dev",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "55",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-10-03 07:37:41",
                "updated_at" => "2023-10-03 07:37:41",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "high periority",
            ],
            [
                "id" => "340",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "NfATWbVsSikfWlOd38KN",
                "name" => "Test224",
                "description" => "WWADADA",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "55",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-10-03 07:38:03",
                "updated_at" => "2023-10-03 07:38:03",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "8 gb ram",
            ],
            [
                "id" => "341",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "bZTUDpNy2WPg6RO1OX0O",
                "name" => "first inventory",
                "description" => "QWERTY",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "55",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-10-03 07:40:31",
                "updated_at" => "2023-10-03 07:40:31",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "12 GB RAM",
            ],
            [
                "id" => "342",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "Aj8d54qlmNWn173OR5gM",
                "name" => "New inventory",
                "description" => "New desc",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "1",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-10-03 07:52:03",
                "updated_at" => "2023-10-03 07:52:03",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "qertyujvbn",
            ],
            [
                "id" => "343",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "4m53p5n33k2jvMzz6DI9",
                "name" => "inventory new",
                "description" => "ghgf",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "1",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-10-03 07:55:09",
                "updated_at" => "2023-10-03 07:55:09",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "gf",
            ],
            [
                "id" => "349",
                "is_active" => "1",
                "signal_strength" => "0",
                "battery_level" => "0",
                "company_id" => "c95sdr1e9seo9ptrpbbg",
                "temperature" => "",
                "device_id" => "vTR3MQvhOKnPQCGyE246",
                "name" => "Test",
                "description" => "WWADADA",
                "device_status" => "0",
                "event_type" => "inventory",
                "user_id" => "1",
                "sensor_id" => "0",
                "transmissionMode" => null,
                "coming_from_id" => "0",
                "created_at" => "2023-10-05 14:30:01",
                "updated_at" => "2023-10-05 14:30:01",
                "battery_updated_datetime" => null,
                "temeprature_last_updated" => null,
                "macAddress" => null,
                "ipAddress" => null,
                "sort" => null,
                "labels_json" => null,
                "not_available" => "0",
                "specification" => "high periority",
            ],
        ];

        foreach ($devices as $deviceData) {
            Device::create($deviceData);
        }

    }
}
